export const IMAGE = {
  arrow: require('../../src/assets/image/lefta.png'),
  cover: require('../assets/image/Cover.png'),
  cam: require('../assets/image/cam.png'),
  footer: require('../assets/image/Footer.png'),
  boxer: require('../assets/image/boxer.png'),
  nxtBtnEnable: require('../assets/image/ButtonOn.png'),
  nxtBtnDisable: require('../assets/image/ButtonOff.png'),
  withNumber: require('../assets/image/withNumber.png'),
  withUsername: require('../assets/image/withUsername.png'),
  biker1: require('../assets/image/biker1.png'),
  biker2: require('../assets/image/biker2.png'),
  saveEnable: require('../assets/image/saveActive.png'),
  saveDisable: require('../assets/image/saveDisable.png'),
  getCodeDisable: require('../assets/image/getCodeDisable.png'),
  getCodeEnable: require('../assets/image/getCodeActive.png'),
  fan: require('../assets/image/fan.png'),
  athlete: require('../assets/image/athl.png'),
};
