export const STRINGNAME = {
  AGREE: 'I agree to the',
  ALREADY: 'Already a user ',
  ATHLETE: 'ATHLETE',
  CORRECT_NUMBER_MSG:
    'Please enter the correct mobile number \nassociated with your account \n\n',
  CORRECT_EMAIL_MSG:
    'Please enter the correct username associated \nwith your account\n\n',
  CONFIRM_NEW_PASSWORD: 'Confirm New Password',
  CHNAGE_YOUR_USERNAME: 'Change your Username',
  CREATE_ACCOUNT: 'Create Account',
  CONTINUE: 'CONTINUE',
  CONTINUE_WITH_GOOGLE: 'Continue With Google',
  CONTINUE_WITH_APPLE: 'Continue with Apple',
  CONGRATULATION: '\nCONGRATULATIONS\n',
  DID_NOT_RECEIVE_CODE: "Didn't received the code yet?",
  ENTER_NEW_PASSWORD: 'Enter New Password',
  ENTER_VERIFICATION_CODE: 'Enter Verification code',
  EMAIL: 'Email*',
  EDIT: '   Edit',
  FAN: 'FAN',
  FULL_NAME: 'Full Name*',
  FIND_ACCOUNT: 'Find Your Account',
  FORGOT_PASSWORD: 'Forgot Password?',
  HI_JOHN: 'Hi John! \nTell us about yourself',
  I_AM_NEW_USER: "I'm a new user ",
  I_AGREE: 'I agree to the ',
  INVALID_CRED: 'Invalid credentials',
  KINDLY_ENTER_CODE: `Kindly enter the 4 digit verification code sent to`,
  MOBILE_NUMBER: 'Mobile Number*',
  MOBILE_EMAIL: 'Mobile Number / Email ',
  OR: 'OR',
  PASSWORD: 'Password*',
  PLEASE_CREATE_A_NEW_PASSWORD: 'Please create a new password',
  RESET_PASSWORD: 'Reset Password',
  RESEND_CODE: 'Resend Verification Code',
  SIGNIN_HEADING: 'Sign In Using Your Mobile Number / Email',
  SIGNIN: 'Sign In',
  SIGNUP1: 'Sign Up',
  SUBMIT: 'Submit',
  SIGN_UP_TO_GET_STARTED: 'Signup to get started',
  SOME_MOST_FOLLOWED_ATHL: 'Some of the most followed \nAthletes',
  SELECT_OPTION: '\nSelect an option to find your account\n\n',
  SPORT_I_WATCH: 'Sports I Watch',
  SELECT_YOUR_IDENTITY: 'Select your identity',
  SEARCH_SPORTS: 'Search Sports',
  SIGNIN_USING_MOBILE_EMAIL: 'Sign In Using Your \nMobile Number / Email',
  SEARCH_FOR_ZIPCODE: 'Search for Zip Code',
  TERMS_OF_USE: 'Terms of Use*',
  TOO_SHORT: 'too short',
  USER_NAME: 'User name',
  WHAT_SPORTS_DO_YOU_LIKE: 'What sport do you like to play?',
  WHO_ARE_YOU: 'Who are You?',
  WRONG_OTP: 'Wrong OTP',
  YOUR_ACCOUNT_SUCCESSFULL: 'Your account has been successfully \nregistered',
};
