export const STRINGNAME = {
  AGREE: 'I agree to the',
  ALREADY: 'Already a user',
  ATHLETE: 'ATHLETE',
  CORRECT_NUMBER_MSG:
    'Please enter the correct mobile number \nassociated with your account \n\n',
  CORRECT_EMAIL_MSG:
    'Please enter the correct username associated \nwith your account\n\n',
  COMPLETE_PROFILE: 'CompleteProfile',
  CONFIRM_NEW_PASSWORD: 'Confirm New Password',
  CHOICE_PAGE: 'ChoicePage',
  CHNAGE_YOUR_USERNAME: 'Change your Username',
  CREATE_ACCOUNT: 'Create Account',
  ENTER_NEW_PASSWORD: 'Enter New Password',
  EMAIL: 'Email*',
  FULL_NAME: 'Full Name*',
  FAN: 'FAN',
  FORGOT_PASSWORD: 'Forgot Password?',
  FIND_ACCOUNT: 'Find Your Account',
  HI_JOHN: 'Hi John! \nTell us about yourself',
  I_AM_NEW_USER: "I'm a new user ",
  INVALID_CRED: 'Invalid credentials',
  LOGIN_SCREEN: 'LoginScreen',
  MOBILE_NUMBER: 'Mobile Number*',
  MOBILE_EMAIL: 'Mobile Number / Email ',
  OR: 'OR',
  PASSWORD: 'Password*',
  PLEASE_CREATE_A_NEW_PASSWORD: 'Please create a new password',
  RESET_PASSWORD: 'Reset Password',
  SIGNIN_HEADING: 'Sign In Using Your Mobile Number / Email',
  SIGNIN: 'Sign In',
  SIGNUP1: 'Sign Up',
  SIGNUP: 'SignUp',
  SIGN_UP: 'Signup to get started',
  SELECT_OPTION: '\nSelect an option to find your account\n\n',
  SPLASH_SCREEN: 'SplashScreen',
  SELECT_YOUR_IDENTITY: 'Select your identity',
  SEARCH_SPORTS: 'Search Sports',
  SIGNIN_USING_MOBILE_EMAIL: 'Sign In Using Your \nMobile Number / Email',
  SPORTSLOGOSCR: 'SportsLogoScr',
  TERMS: 'Terms',
  TERMS_OF_USE: 'Terms of Use*',
  TOO_SHORT: 'too short',
  USER_NAME: 'User name',
  VALIDATEOTP: 'ValidateOtp',
  WHAT_SPORTS_DO_YOU_LIKE: 'What sport do you like to play?',
  WHO_ARE_YOU: 'Who are You?',
};
